spring:
  application:
    name: service-zuul


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka
zuul:
  routes:
    api-ribbon:
      path: /api-ribbon/**
      serviceId: service-ribbon
    api-feign:
      path: /api-feign/**
      serviceId: service-feign
server:
  port: 8130
